// Input: First line k and t. Next lines, a list of error-prone reads
// Example input: 3 3
//                AACG
//                AAGG
//                ACGT
//                AGGT
//                CGTT
//                GCAA
//                GGTT
//                GTTG
//                TGCA
//                TTGC
// Output: Given a bubble length threshold of t, detect (v, w)-bubbles in the de Bruijn graph generated
// from k-mers of the reads.
// Example output: 1

let PROFILE = false;
let VERBOSE = false;

const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  terminal: false
});

const readLines = () => {
  process.stdin.setEncoding('utf8');

  const reads = [];

  rl.once('line', line => {
    const [bubbleThreshold, k] = line.split(' ').map(v => parseInt(v, 10));

    const readLine = (line, prevTimeout) => {
      reads.push(line);

      if (prevTimeout) {
        clearTimeout(prevTimeout);
      }

      const newTimeout = setTimeout(() => {
        process.stdout.write(getResult(bubbleThreshold, k, reads).toString());
        process.exit();
      }, 300);

      rl.once('line', line => {
        readLine(line, newTimeout);
      });
    };

    rl.once('line', readLine);
  });
};

function checkAComesBeforeB(a, b) {
  let weight = 0;
  let windowSize = 0;

  while (true) {
    windowSize++;

    const query = a.slice(-windowSize);

    if (b.substring(0, windowSize) === query) {
      weight = windowSize;

      if (windowSize === b.length) {
        break;
      }
    } else {
      break;
    }
  }

  return weight;
}

function buildDeBruijnGraph(reads, size) {
  const graph = {};
  let lastRead = '';

  reads.forEach(read => {
    const maxWindowIndex = read.length - size;

    for (let i = 0; i <= maxWindowIndex; i++) {
      const curRead = read.substring(i, i + size);

      if (!graph[curRead]) {
        graph[curRead] = new Set();
      }

      if (lastRead) {
        graph[lastRead].add(curRead);
      }

      lastRead = curRead;
    }

    lastRead = '';
  });

  return graph;
}

function dfs(graph, startNode) {
  const order = [];
  const stack = [startNode];
  const visited = new Set();

  while(stack.length) {
    const currentVertex = stack.pop();

    if (!visited.has(currentVertex)) {
      visited.add(currentVertex);
      order.push(currentVertex);

      const neighbors = Array.from(graph[currentVertex]);

      neighbors.forEach(destiny => {
        if (neighbors.length > 1) {

        }

        if (!visited.has(destiny)) {
          stack.push(destiny);
        }
      });
    }
  }

  return order;
}

function findAllPaths(graph, startNode) {
  const stack = [[startNode]];
  const paths = [];

  while (stack.length > 0) {
    const path = stack.pop();
    const lastNode = path[path.length - 1];

    for (let neighbor of graph[lastNode]) {
      if (neighbor === startNode) {
        paths.push(path);
      }

      if (!path.includes(neighbor)) {
        let newPath = path.concat(neighbor);
        stack.push(newPath);
      }
    }
  }

  return paths;
}

function getResult(bubbleThreshold, k, reads) {
  const graph = buildDeBruijnGraph(reads, k - 1);
  const firstRead = reads[0].substring(0, k - 1);
  const bubbles = findAllPaths(graph, firstRead);

  return bubbles.length / 2;
}

function generateRandomRead(size) {
  const letters = ['A', 'C', 'G', 'T'];
  const read = [];

  for (let i = 0; i < size; i++) {
    const randomLetter = Math.floor(Math.random() * letters.length);
    console.log(randomLetter);
    read.push(letters[randomLetter]);
  }

  return read.join('');
}

function test(outputType, onlyTest) {
  let testCases = [
    {
      id: 1,
      run: () => getResult(
        3,
        3,
        [
          'AACG',
          'AAGG',
          'ACGT',
          'AGGT',
          'CGTT',
          'GCAA',
          'GGTT',
          'GTTG',
          'TGCA',
          'TTGC',
        ]
      ),
      expected: 1
    },

    {
      id: 2,
      run: () => getResult(
        3,
        3,
        [
          'TGCTCTGCGAATAGTGAGCCGATCCCCCGGGAGCGCAACAAACTGGTATCTACAGTCTCCGTGCGTGAGCGACGCGCTCTCTGATAGCTTACGATTACTG',
          'CATTAGACGTATTTGTCAGTCTTAGGGCAATAAGTCTCCCTCAACGGAGCCGTGGTCCCATGTTAAAAACAACCCTGGCGCTTTGTTGACTTCATTCGTG',
          'CGAGATATAAGGCTTCGGCTTGTTCGATGATCCTGAAGGTCTACTGTTTCTTAGAAATTCAGTGCAAAGCTTACGAGGAAGCCTACTCAGCGCGTTCAGC',
          'GGAGAGATCAAGTCAACTATGAGAGCATTACGGATTGATGGGCACAGGGCACGGTCTAGGATGGCACTTGCGCTACGGAACCCGCTACTCCTAGCGTTAT',
          'GACTAAGGTAATAGCACATGAAGTGCGTCGAGACGGAGCAGGCCCTGGGGCAGGCGGTTTCTTATTCACGGTTTCCTACCTCTGCGCTTTCATGAATTTA',
          'CGATACACAGACCTTACTGATCAGGTTCCAATCTTGATAGCACCACCGAACACCAATTCGCCCGACACGCGAGAGCAGGTACATGTTAGTGGTAGGCAGT',
          'TACCATTCACCTCTAATACTCGGTAAAATGTGTACAAATGGCAGGCAAGGCCTGCTACTAGTAATATGCCGCAGCTGTTGCTTGTCACACTGAAACCGGC',
          'AAGTCCCATCAGTGACAATATGACACCTCTGCAGGGATCTCAATACCGTGTCAACGAGAGGTGGACCCACCACTCCTGTTGTATAATCATTGATATAAAC',
          'TAATCTAATCTCAATCTAGTGCACAAGAGCCCTTCACCAGCCTCAATACTTCCAGGCATCCAACATAACGTCAAGAAGATACCGGTTGTCTAGGCCTAAT',
          'CGTTAGGAGATCACCGTTTAGTCAATCCTGTACAGGGGGTGCCAGACGATATCCGTAAGCGTAAAAGAAGCGTCCGCAGGTTGTATAGGTCATCATTCCC',
          'CAGCAGGACTTTTTTACAATTCCTGGCGTGGATCCGGTCCGCGAGCGATTCGCGCTCATCATCCATCACGTTCCACAGAGGCTGTTGATAACCTTGAACG',
          'CTTAGCTACCATCATTACGGAGACCACTCTAGTAGGACAACATCTATTGTATGACGCCCTTCTCTGTATCAGAGCCTGGCCCTCACGGGTTGATTGCTAG',
          'GCTAACTCACTCCAGTGCCTAGTCATAAGGGTGAAGGCAACGGACGACACAGACCCCTGAATGCCTTACCTGGACCTTCGTCGTGTACACGGCTGACCCG',
          'GGAGTCTGGGATCGAGGGCTGCGATTGACCGCGAACGACATGTTAGTCCACAGGCGCCGGTAATCATGCTCAAAACCGGCTCTTGGTAAAGTGAAATCTT',
          'TCAGGCGCGTCGCTTGAACCTCGTCGCCCGCTTGTGGTGTTAAGGCAGGTGTTTCTAAAACGGAAATGCCGCTAATTGACCGTCACGCAGCTGCGCAACG',
          'TTGGTTGTCCACGAAACACACGCACTTTATGTTTGGGGTTTTGATTCAGGTGCTTTGCGTCCCCGCGGTAACAGGCGAAAACCTTGCTCATATCGCAAAC',
          'GACATCCAGGATATCACATGATTGAATAAAACTGAATTACATGTTGTGCGAGAGTGCCATTCTGATCATGCAATTATACTATATCTCGACGACGACGGTT',
          'CAGGCTCGTAAGCCCCTTGAGTTGGCGGGTACGTGCTCGTCCTAGGAAGATGAGTTTTGGGGGTGCATACCGACCTGCCGGTCGTCAGAACACGCCACAC',
          'GGAATGTCGTTATGCGGCCAAATTGACCGGCTGGGCTGAGCAGCAACCCAATTCCTAGAGACAGGGCACTGGCCGTGGAAGTCTTCCTGCTTTTTCGCTG',
          'AGGAAGGGTTATCCTCGTGTACATAGCTCAGTGCCCGAGTAGTGCTTGCCTGGGGGGGTGCCTTACCGCTAATGGAATGGAAGGGCCTGGACTGTCCCCT',
          'TTAGACAATTGAGAGCAATCAGGTTTACGGCTAGTTGTGTAGTGAAGCGGCATGTCATATCAATGTGATTACCCGGTTAATGAAGCTCTTAAGTTGTCAC',
          'TGGACAGGCAGACGGGATCCCTATTCAGCAATAGCTTTGGGGTTTCGGGTGTCATGCTTACGGAGGCGATGCCCTAACGTTTTCAACGAGAGGATTGCTG',
          'AATCACTCCGCAGACAGGTTTTGGGGCGGCTCGCTTTCCTATGCCCCACACTTCAACTTAAAATTGAGCGGACCAACGTACATGCTTCATTTCGCGACCT',
          'TCCAGGGACGCCCAGATGGAAACAACACCATGCAATTCTACCAAACCTGCGTTGGGACCCTCGATATGTGGCGACGGGGCTAGTCAGACCTCACGATTTC',
          'GGCTTACTAACAGGTGGTCCTCATCGTGTCCAAATGGGCCACAAACCCCAAAACCGTACTCCTGTCGTTGTCGGTCTGAAGAATCGATCCATCACTGGAT',
          'TAACCCTCAAGCGTCATGATTGGTGGCATAGAGCCAACAACAGTCTGCGTACAAATTTACCATGGAGCGTCATCGTCCGGGGAGTCAGGACCCAAGCCAT',
          'AAAACCGGATCATCGGCAACGCGACGTTTTTATCCACGCAGCAAAGAAAACAGGAATATCCCGTAAGTCATATGCAGGTCGTTGATAATCAAGTTGAACT',
          'CGTGTTTCTCGTATAAGCCAACGTACTGGGAACCATAGAAGCAAGGCGATGATATTAGAACCGAGAAGTGAATGCCGGAGTGCGTAACATAAATGAATCT',
          'GCGACGTTGCGTTCGGCGCAGATTGCAAGCTATGAGGATGTGGCTCCAATGGCAGTCAGCTTTGCCGACTTCTAACGTAGGTTAATGGTACCAGCTTCGT',
          'CCCTGGTTCTGCAGTACTAGGTCCACCACCAAGTGGGTTGCTCCTTGTATTGTTCCACTCCTGGCCCGTACTTTGCCAGTCTGTACCATTGTACGTGAAA',
          'GTTTTCATAACTACGTGCGAAGTTTTACGGTTGGAAGCAGCCACGAGTGATATACCCCGACGCTTCTGTCTAATCGTCTACACTGGAAATAGGGTCGGCA',
          'TTGGAACCTGATTTAGTCGCCTTATGCGTATCTGACTCACCACTCCGCGGGATAAGGGGCCAGGAGCACCAGTTAACCGTGTGATTAGACCCAACATCGG',
          'GTTGGCAGGGGGCAGAAGTACGACGTTGATCCGAGAATTGCAACCCACTGCTCAAAGCGTTGCGTGGCCTAATCTCGTCCCCTAATTGTCGAGAACCATC',
          'ATATCTTATCAAGTGAGGGTCATGCTTAACACCAACGCCGTTGGTGAGCCGATATTGGCCCGGGTATGAAATCATCGTGGTTCATTAGAGCTCTAGCCCG',
          'TCGGAGTCTCACCGTATTTGGTCTCGACACACGTACCGAGTACGGCGATTTTCGTTATTCCTAGTCCATATATCTTGGGAGTTTTGTCTCTTTGTGATTT',
          'TAGTAGTTCTCGCTGCATAAAAAGCCGGTTTCATAGGAATCATTAGTAGCCAAGTTGAGCGATGCTAATACGTTCTGGATACAAATCCACCCATTCCTAG',
          'TTGGGGAAGTGAAGTGTACTTTGTTTTCTCCGCCACCGCCTTCTTGACATATAAATTAGAATTTGCACGCGGCCCCTAAAGATATTAGTGCCAAGAGATA',
          'CCCTACCCACACCTCGCACGACTGGAGCATGATGGCCCGTCTTAAAGGTCACTATTGTAACCCTCGTGCTTAGAGCCGAGTTGGTCAGGCAGGGCAGCTT',
          'TCGCCAAGAGAGTAAATACATTATTGCGTTTCTGTCAGTATGCAACCTACGGGCTATTAGACTAGGCTTTCGCCAATGAGACCTCTGCACGGTAGGTACA',
          'TCTGAGCCAGCCTCTTCTGCACAGAACTCTGCGTAGACTACCTGCGATAGTGGCGACCATTTTCCCGGATAACGTTTATGCCGATTTCCAATCCAGCGGA',
          'TGAAGTGTCGGGACATTAATCGCTTACAGGAGCAGAGTGCAGAGCGAATAAAGTCATCGGCCGCCTGATACTGAGCCGCGGATGTTCGCAAGTGATGATG',
          'ATACCTTTGACACCAATTTCTAACTTCTGAGTGCTCGCCCTTCGAGCGCCCCCGTTTGGGAGGTACCCGAGAGTTCTGTGTTACACCGTGGGTGGCTGCG',
          'CGTGCACTAGAGCCACGATAGGCGCAACATCACTATACCGCTATCACCTTGCTCCCGTGTCGAAAGAAACCCTGCCTACAACTGCCAAACGAGGTTTGTT',
          'GGGGATACGATGCCGTGTGATAGCCGATGGATGGCAAAGAAGGACGGTCCCACGCCAACGGTACTGCAAGCATAGATTCGCGCGGCGTGGTGGGGCAGAA',
          'GAATTACGAGACTTCTTAACCGGAATGTCGCGCGGTTACTAACCCGGCCGTAGAAGCCACTAACTGGACCGGAATTCGCACCTAGGCTATCGGTCTGTGA',
          'CTGCCATCCTAAGGCCATATACGTAGCCCCGTTGCCAATAGGGTCCCTAATAGATGATCTTGCGTAGGTGGGGAGAGTACATACTCGAATCCACGAGCGT',
          'TAAGTATCAAGAGCTGATCTATGGCGGTGAACACTTTGTTGCGTCCTGGGGTGGCCAATTTCGTTAGGCAATGGTTTGAAACATAACCTGAGATTATAAA',
          'CGTAATCAAATATTACATTCGAATCTGCACTATCTCGCCTCTCCGAGGGATAATTGCAGGTCGGGGGAGTTTGACGTTAGGCTAAGTACTATAGGCCGTC',
          'AGTCAGACCCCTTTCAGTTGCTACCCAAAACCGATTCGTAATCGGGCGCGATAGCTTTGGTTATCAGCAACAGGGCCGCCACTCACGTAGCCACACCACC',
          'GAGTACCTCCGGAGGTATTTATTACTCTTTCGTCCCACTAAAGCCTCGCGCGCTAGCCGAGAGTGGCGCCTGCGTTAGCGATTATTCGCTATTTTGAAGT',
          'ACGGGGGCGTCTCGTTCTGATAAACACTCGCCGGCGGTCGAGATTGGGCCTCGCGCTCGGTACGTGTAGCCTGGAGGGGGTTTCGTGAGAAGACCGGAGC',
          'GTCGGGCTGCGATGCTCCACCACAGTAGGCTTGGAGGGTCTGTTGGTAAACGCAACCCTATACCCGTACGAGATCTTAATGACTAGGCTATATTTCCGAA',
          'TGGAACGCGTTGCACGGACAGACATTAATCGTCGTAGTCGTCGAAGCCTGCGTGTTGCGGCATGCGTGATAATTCAGCATGCGGCCGTGTTAGCCAAGAT',
          'AGATCAGAAGTAGGGGTCCGGCGCGATCCCGCGCTCCTCCTTGTAGTCCAGGCCCCCATCGAGCCTATACGACCGGGGCGCCTACCTCAAATTTGTATGG',
          'ATTTACTTTGGACCGCGCGCGTTGCCGCGGCTCTGCGCACCCCACAAAAATAGTGGTCCACGGAACTACCGGATGTATTTCTAACTAGGGTCTGATATGC',
          'ACGCCTTGCTGCTGACTTACCAAGCGAACACCACGGTTTCTTCCAGAGAGGCCCTCGTAGCGGTAGTTTAGGGGTTAGCACAGTACGCCATGCTCCTTCC',
          'CGACTAAAACCGAGCCCGGGTTAGCATTGCTATGTTTCCACTCGGTGCATGATTCACTACCGTTATGACGTATGGGGGGAGCGCGCAGAGCGCGGTAGAG',
          'TCTGTACCCCGTAGTGACTCAAGCGCCGCAATCTGTTCGTTCTGGAGGAACCCCAGGTAAAAGAGTCCTTAGGCCCTAGGCCGTGTTGAAATACTGATGC',
          'TCTTCTAGATTTTTCTGGGTATTGAGTTTGTTGTGTAGACATTAGCCCGCGATGGTCGTTCCTCATTACAACAGTGTCCACGGCGAAATTTGTGAGCTAA',
          'AGTGTTAGTCGTTCATCGTTAATCCCAAGTGTTGTTGTTAACTTTTGAAGTACAGTCGGGAGGCCAGACCTTTAAAGATAGGGGCCAGGACTTTTACACT',
          'CGGCTCCCCTCTCAGCGTAGATCCCGTACATGGGAAGAATGCACTTGAGTAGACTCGCAATCTTCTTATTGCCCATTAAGCGCATTCAGCTGGTCCAGCT',
          'CCATCCGCAAGAAGAAGCAGGAGCAGAAGGTCCCCCTAGATTTAACAAGATTTGACGATTCAATGTCTATAGTACCTTGAATGGCGCGGCAAGAGTAATT',
          'TAAGCTCGAATTCCAAAGTCCAGGATGAGGTAGCTTGTCTACCTATCGAAATAACTGCACTGTGCAAGCTGTTACTGAGAAGGGCGATAGCCACCAGGCT',
          'CTGAAGTTGCTCAAGGCACCCATGCTATTCCAGGTCCAAGTCCTGCTCCCTCGTAGTATCAAGATCAAATAACCTCAAAGCATCCCTTGTGCGGCGTTCT',
          'TCTGGGTACGCGGGAGATGAATCTCTGCGTATCCGGGAAGCCTGTGACCGCGATGTACTGACCGGGAGCACTCAATTATCCACGCACGCGTGACCTTCAG',
          'AGAGCATATACCTACTGTTACCTTTGGCGCTCGTCGCTTAATTAATACACAACCAGACGAATGAGGTACCCATTGCAATAAAGAGTATCATTATGCATTG',
          'CACTCCATAAACGGACCGCCGAGCCGAAATGTATAGCCTCTTTAGAATTATCTTTGCAAGCCAGGATACCCAATATCTTTTTAGATCAATATGATTCTTG',
          'AGCTTAGCGCTCACAATCTCAGAAAGTTGGTTGTACGTCTGACCTAGAAGGTCCTGGGCTACATGTAACCTGGGCAGATTATGCGAAAGTCCGTGCTGAC',
          'GAGACAATCTATTACGAACAGCCCTGTGTCCAGCAGTTCTTGACACAGATCAGTTTAAATGTTCTAGACCGCGCCTTCGGGATCCACTTTGACGCCAGGG',
          'TCACGCGCGTACATGGTCGATTATGGTACAGATTAACAGCGATATGATCACCGCACACCCCCCCTTGGACCAATTGGGACAGACAGATTGGTGGTACTGA',
          'TACTTGGCTCTTGCGCGCCAGTCCCCCTTAGACAAGTGCGTAACTGCTAGGTCCTAAGACGCGCGTGATGCTCTGGATCATGCACATGGGATCAAACTTG',
          'GCTTCATTCCTCCCGGAGTAAGCTGCCCGCGGGGCGTGGAAACTGACCATGAGGGCTTCGGCCTTTGTTTGGCCCAATCTTAAGTAATGTGGCCCATAGA',
          'ACGACCAGCAACCTATTGACAGCTGCGTAGATGAGGGCGTTTTGTTGTTAGCCATACTATCGGACTGCTTGAGAATTCCCTATCACGCTGCCCTCTCGGG',
          'ATGGAATACCGGCGTTAGTGATAGCGTTCACTCCTCGGGAGCAGAGGCCCTCAGACCACGACGCATCCGCGGAGCTGGTAGGACGATTTTAGAAGTGGCA',
          'ACGTCGCTCGATCTGCGGAAAACAGTAACGACACAGAATCAACTTGTGACTATCGCTCCTTTGTACGCACCGATTGTTGTGCGCCCTACGGACGGCATAT',
          'CCGGTAAAGCGGGCATGCTAAAGACGCTAAAAAAAAGCGCAGGTATCACTGTAACGCCCCCCGCTTGTAGCGAGAAATCTGAGTCCTCCCTCGGCGGTTA',
          'CAATCAGGCATCTATATGCGCAATATAACCGCACCAAGGTATGCCGCTAAAAAACCGCGGTTTTAGGATGCGTTGCTCCATTCGCGCCGGCAATGTGTTA',
          'TCATAGATGGCTCGCTTCCGCCTAGAATGAGGCTGGGGCAAGGCCCAGACTCAGTGGGGACTTAGCCAATAAAGGGGGTGGAAATCGCTCTATAGTAGTG',
          'GTTCTAATTTGCGTCGGCTTATAGGGTCCCTGCGTTGGCACCAACTCAATAATTAGTTTGGTAATTATTTTAGACGTGGTAAGTTAAGGCCACATGCCAT',
          'TAGGGGTCGAGTTAGAGTCCGTTATAGATGCTCTGCTCGGCAGTTATTTGCAACCAGAGACTGAGGTCAATAAGGCCACGGTAACCTTTCCTGCGTGGGT',
          'GCGGCTAGAACGATAAGTTCGCAACAGCGCTAGGTGAGCCTAAAAGATGATTCCAACGCTGCGCATGTAATATCCTTGATGTATCACATTTTGACTACCA',
          'TTCACAAATCACAGAGGGGACGCTATCTAAGATGATCACAACACAGTTAGAAGGTCCCTTAGATTCCCGGCTAAACTAACTATTGTTCTTACTACTGAAG',
          'CGTACCCACCGGAGCGGTATCGCGCCTAATGATGTAACAACATCTGGCTCGCGAGATCATCAACGGTGGACAATGAGAAATGTACATAGAGTCAATCCGT',
          'GCGCTTTCGAGTACCTCAGGCGTCGACCTTATTCCCTTGGGACGCGGGCCGCGAACGTTATAAAGCATCGGCATGTACTCTTCAGCGACCTATTCGGATC',
          'TTTCCAAATTGGGTAAGGCGGAGATATATCTCTCATAGCGTGGTTGAGGCTGCGTCCGTTAGCCACAAGGCGTCCCTGCTTTACAGTATTGTTTAGCCAA',
          'AAGGGGATGTTGTCCTTCGAAGCGACCACGCAGTTCAAAGAGGACTTCGGCCCGTGTTTGTTACCTACGAGTCGTCGCCGTATGCCGTTTCCGCAAAGTC',
          'AGGCGTAGTCCTATCAAGGCTGTAAAAAGAAGCATAATGTTACAAGCATGTTCTACCTAATTAGCACAGTAGACATTGTAGACCTCGTTTCGAGGTTTTT',
          'CCCCACCACCTCGCAACCCCACAGTTAGTCATCGCGAGTGAAGCCTTGCTCCCGAACCGTCGTTACACTATAGTTCCTAACCGATTATTATGTGCTCACA',
          'GCTGGCATCTCAAGACAGCGCGTCGATATCGTTGTCTGCCGTGGTTCGAGGGATCATACTATTGACGGCTGAGACCTGGTTGCCAAGTCCACCTGTCACA',
          'CCTTACCACAGAACCACTCGATAGTCGCATCATTTGCCCGTCACACGGTCTCAGTACACACCGAAAGTCTCTGTGATCCGCGGTCGTTAATTTCAAAGTT',
          'TATCCAATCATTAAGAAGTCCCGTGTTCGGAGAGACAAGTGCTTAATTTCCCCCTTGTGACCATAGAACGCGTCGCTGGGGGGGTGTATATATACCCGTG',
          'TGAGCAGTTATAGCTTTGTAGGGTCACGTACCGCCTGAATCATAGCGATCTACAGCCGGGGATCCAGAATTGCTTACACTAGAGCCGCTGAAGGGTCGCG',
          'GGAAGTCCCCGTGGATACGAAAGTGCACCACGTCACTAAGCTATCGTACATCAAGACAGGCTTTTGCCCGTCTGTTCCGGCCAACGCGGCCTTATATCAA',
          'GCACCACTCCCGATGGCTGTTATCGGTTCCCGGAAGATAGCATGGGTTCTCGATTAAGTAAAAGGGTGGGAAGATATATTATTCGGATAAGACGCTGTTA',
          'CGACCTTCAGGGGGCTGATCTTCGTCGACGGGACATTAAATGCTCATTGCGGTTCATTAGAATGTGACAAGTGACACCACCAATCGCATTTTTTCGATGT',
          'ACAGTGAGCAGTGTGGGGCTACGGTCAGAGCGGAAACCCTATGTCGATACCAAGGTAGCCACGACGCCGTCACATACACGGAGTTCCCGTCGGAATTCAG',
          'AGTTGTAACCACCCTTCAGATGTGTGACCTGACATTGTGTTCCCCGACGACTCCGCTGCTGACAATTCCTCGCTGACCGTCCTTACGTGGTTTCTATAAG',
          'TTCAGTCGACATAAAAGGAATTGATGTCGCCTTCAAAAGAGTCCGCCCGACTATCGATTCCTCTGACCATGACTCGTATGGCCACCCCATCTGAAACACT',
          'TGACCTGCCCAGCCTGGGGTCTTTGCCGACTGTCCACGCATTCAGCGCAACCTATCAGGTACCCAGACTCAGAGAGCCTGTTAGGTCGTAAGCCAAGAAG',
          'TCAAACTTGGAGGCGTATGAAAATGGTACACTGAATGTTTGGGATGTGTAAACGCTCATAGGCGTCAGGGGGAAGTGCCACCGACTCATGTTAAATATCA',
        ]
      ),
      expected: 3
    },
  ];

  if (onlyTest !== undefined) {
    testCases = [testCases.find(testCase => testCase.id == onlyTest)].filter(test => test);
  }

  if (!testCases.length) {
    console.log('No tests found!');
    process.exit();
  }

  testCases.forEach(testCase => {
    const result = testCase.run();

    if (outputType === 'RESULT') {
      process.stdout.write(result.toString());
    } else if (outputType === 'TEST') {
      if (result === testCase.expected) {
        console.log(`[V] Passed test ${testCase.id}`);
      } else {
        console.log(`[X] Failed test ${testCase.id}`);
        console.log(`Expected: ${testCase.expected}`);
        console.log(`Got: ${result}`);
      }
    }
  });

  process.exit();
}

if (process && process.argv && process.argv.includes('-t')) {
  const onlyOutput = process.argv.includes('-o');
  const silent = process.argv.includes('-s');
  const indexOfT = process.argv.indexOf('-t');
  const testToRun = process.argv[indexOfT + 1];
  let outputType = 'TEST';

  if (onlyOutput) {
    outputType = 'RESULT';
  }

  if (silent) {
    outputType = 'SILENT';
  }

  VERBOSE = process.argv.includes('-v');
  PROFILE = process.argv.includes('-p');

  return test(outputType, testToRun);
}

readLines();

module.exports = getResult;
